sudo: required
services:
  - docker
  
before_install:
  docker build -t vladbronfman/react-test -f ./client/Dockerfile.dev ./client
   
script:
  - docker run -e CI=true vladbronfman/react-test npm test 
  
after_success:
  - docker build -t vladbronfman/multi-client ./client
  - docker build -t vladbronfman/multi-nginx ./nginx
  - docker build -t vladbronfman/multi-server ./server
  - docker build -t vladbronfman/multi-worker ./worker
  #log-in into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take images and push to docker-hub
  - docker push  vladbronfman/multi-client
  - docker push  vladbronfman/multi-nginx
  - docker push -vladbronfman/multi-server
  - docker push  vladbronfman/multi-worker
  
  
   
 