sudo: required
language: generic

services:
  - docker
  
before_install:
  docker build -t vladbronfman/react-test -f ./client/Dockerfile.dev ./client
   
script:
  - docker run -e CI=true vladbronfman/react-test npm test 
  
after_success:
  - docker build -t vladbronfman/multi-client ./client
  - docker build -t vladbronfman/multi-nginx ./nginx
  - docker build -t vladbronfman/multi-server ./server
  - docker build -t vladbronfman/multi-worker ./worker
  #log-in into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take images and push to docker-hub
  - docker push  vladbronfman/multi-client
  - docker push  vladbronfman/multi-nginx
  - docker push -vladbronfman/multi-server
  - docker push  vladbronfman/multi-worker
  
 #deploy to AWS
 #MultiDocker-env.eba-ehgntau5.us-east-2.elasticbeanstalk.com 
deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-451561843959
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  
  
  
   
 